### ISSUE TITLE
`probability_two_random_records_match` shouldn't have a default value

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#1069]
### What happens?

I've been using splink for a bit, and I just realized I hadn't ever been fitting `probability_two_random_records_match`. Everything happily works and there are no warnings, even though the default value of 1/10_000 is almost definitely wrong. If I understand correctly, this parameter determines the "prior", which all of the probabilities use as a starting point, so all my final match probabilities are also incorrect.

I think there should be a warning when you try to .predict() if you haven't fit this param, similar to when you haven't fit a particular m or u parameter. (BTW, I love that splink does these warnings, really helps with keeping you from shooting yourself in the foot)

### To Reproduce

Never call `Linker.estimate_probability_two_random_records_match()`, then call `.predict()`

### OS:

all

### Splink version:

3.6.0

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RobinL** [comment]
I agree there should definitely being a warning if you try and `predict()` without having fitted this param.

Just for background info: There are various reasons we use defaults for the various params:
- They're needed as starting values for the iterative EM estimation process.
- In some cases, a particular param cannot be estimated from the data because the scenario never occurs in the data.  This really only applies to m and u probabilities.  It's not great to have a default values, but it prevents the `predict()` step failing e.g. on new data where that scenario does occur.
- m values are hard to estimate.  In many simple use cases, the user could get away with not bothering to train the m values at all, and just use the defaults.  So long as the prior and the u probabilities were trained (which doesn't require EM), the model would probably give quite good predictions.

Some expert practitioners I've spoken to actually don't use this parameter of the model at all.  If you 'don't use it' (by which they mean setting the prior to 0.5, or 50% probability), then the interpretation of the model changes.  The interpretation of the final prediction (match weight) becomes more like "does the information in the columns add or subtract evidence about whether it's a match".  

Part of their rationale is that, since the conditional independence assumption behind the fellegi sunter model is almost always false, the 'match probabilities' produced are no reliable probabilities.  So you might as well just use match weight as an arbitrary ordinal score.

Personally I disagree with this because i think in well specified models, the match probabilities get fairly close to true probabilities in many cases (enough for them to be interesting).  And also that setting the prior correctly makes EM estimation converge more reliably.
