### ISSUE TITLE
Access to m_probabilities for comparison users

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1104]
Conversation from #1094 

> @[ThomasHepworth](https://github.com/ThomasHepworth) ThomasHepworth [yesterday](https://github.com/moj-analytical-services/splink/pull/1094#discussion_r1129252348)
> A slightly wider point - do we want to allow access to all of the underlying m_probabilities for users? It makes our comparison functions harder to interpret.
> 
> Member
> Author
> @[RossKen](https://github.com/RossKen) RossKen [yesterday](https://github.com/moj-analytical-services/splink/pull/1094#discussion_r1129260464)
> I thought that, but all the other functions had them so I just replicated them here.
> 
> I also wasn't sure exactly why these exist. Is it to make things easier when testing/developing? So you don't have to run EM step to check if these functions work in a pipeline?
> 
> Member
> @[ThomasHepworth](https://github.com/ThomasHepworth) ThomasHepworth [20 hours ago](https://github.com/moj-analytical-services/splink/pull/1094#discussion_r1129527176)
> Yes, originally it was so we could run linker.predict() without any training. I haven't checked to see if this is now no longer a requirement.

Do we still want to have parameters for m probabilities in comparison functions? Or should we strip them out to make functions more difficult to understand?

**Comment by samnlindsay** [comment]
This feature is key to being able to share and run models (or parts of models) out of the box, without retraining, right?

We haven't seen many such use cases ourselves yet, but I would vote to be able to manually specify m probabilities. (Unless I've misunderstood what this discussion is about)

**Comment by RobinL** [comment]
The rationale is basically to do with (1) starting values and (2) whether the user wants to bother with EM.  

On (2), empirically the m values usually matter less than the u values.  So in many applications, you could use defaults, or set them yourself using expert judgement and still get decent results.  

In fact 'expert judgement' for the m values has been seen as a valid approach by academics in the past (though I think it's less applicable when there are lots of comparison levels - it makes more sense if it's just exact match or 'everythign else).

In terms of starting values, the user doesn't need to provide them for the u probabilities because they can be estimated directly using 'estimate_u_using_random_sampling'.  We could add an option to allow the user to provide them.  I didn't mostly because I couldnt' see a scenario in which you'd want to

But for the m values the user might want to set them either due to expert judgement, or because they think they can set better values than the defaults so that EM iteration converges faster

**Comment by RossKen** [comment]
Ok, that makes sense @RobinL - thanks for clarifying!

@ThomasHepworth I'm probably going to close this issue then and say we keep the m-probability parameters as they are in that case. Unless you have any objections?

**Comment by ThomasHepworth** [comment]
Given the above, I think it's sensible to close this and keep the `m_probaility` arguments in the comparison levels.

I was only questioning this as it adds another layer of confusion to these comparison levels, which may complicate matters for users.

Having said that, the m prob arguments are always optional and we are using them internally as a simple way of speeding up model training. 

Perhaps some more information on the documentation around m probabilities and how to take advantage of them would be useful?

**Comment by RossKen** [comment]
Yep, some extra docs would be helpful. Have just been talking to some users who are interested in using it and I realised there isn't too much in the docs
