### ISSUE TITLE
CatalogException: damerau_levenshtein does not exist when using DuckDB

### ISSUE THREAD

**Issue by bingbong-sempai** [moj-analytical-services/splink#1309]
### What happens?

I'm unable to run `linker.estimate_u_using_random_sampling` with a comparison `ctl.name_comparison`.  
The error is"Scalar Function with name damerau_levenshtein does not exist! Did you mean "levenshtein"?"

### To Reproduce

import pandas as pd
from splink.duckdb.linker import DuckDBLinker
import splink.duckdb.comparison_template_library as ctl

df_dupes = pd.DataFrame({
    'unique_id': range(5),
    'name': ['John', 'Johnny', 'Jack', 'James', 'Jimmy']
})

settings = {
    'link_type': 'dedupe_only',
    'comparisons': [ctl.name_comparison('name')],
    'blocking_rules_to_generate_predictions': [
        'substr(l.name, 1, 1) = substr(r.name, 1, 1)'
    ]
}

linker = DuckDBLinker(df_dupes, settings)
linker.estimate_u_using_random_sampling(max_pairs=5)

### OS:

Google colab

### Splink version:

3.9.1

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by ADBond** [comment]
You will need to upgrade your version of `duckdb` to 0.8.0 in order to use `damerau_levenshtein` - `pip install duckdb==0.8.0`.
Apologies, we should probably have some better messaging for this -  we don't insist on this version of `duckdb` as Damerau-Levenshtein is an optional feature, but we should probably make it clearer that this is only available on more recent DuckDB

**Comment by ThomasHepworth** [comment]
Closing as this is now superseded by #1311
