### ISSUE TITLE
Error in subtitle in `em_session.match_weights_interactive_history_chart()`

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#1387]
### What happens?

The blocking rule is encoded into the subtitle as its `__repr__` rather than its `self.blocking_rule`:
<img width="980" alt="image" src="https://github.com/moj-analytical-services/splink/assets/2608005/61ae75d1-f25c-41c5-b9ed-502615444d2d">

### To Reproduce

```
em_session = linker.estimate_parameters_using_expectation_maximisation(rule)
em_session.match_weights_interactive_history_chart()
```

### To fix:

Probably just access the `blocking_rule`property [here](https://github.com/moj-analytical-services/splink/blob/4935a6a48e3fb32003687d748969b96ba3648ce9/splink/em_training_session.py#L315) rather than passing the BlockingRule object into the function

### OS:

iOS

### Splink version:

3.9.2

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by browo097302** [comment]
Hi, I've looked into this and I think I may be able to help.

It seems the whole BlockingRule object is passed into the function so the chart thinks its an object reference rather than a string. I haven't been able to find _blocking_rule_for_training anywhere but maybe the property blocking_rule_sql could work to pass in the SQL string?  
Or maybe the repr() could go around self._blocking_rule_for_training so a more readable string is returned? 

Let me know if you think this may work or if there’s another direction you’d prefer.  

Thanks

**Comment by RobinL** [comment]
Yeah - I think using `blocking_rule_sql` is probably the best solution, consistent with the __repr__ of
https://github.com/moj-analytical-services/splink/blob/cluster_multiple_thresholds_v2/splink/internals/em_training_session.py#L387

Thanks!
