### ISSUE TITLE
deterministic_matching_rules -> rules_to_estimate_prior

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1410]
### Is your proposal related to a problem?

The various rules that a user can define in the training of a Splink model can get confusing as they all do different things (despite the rules themselves looking the same). Blocking Rules are being addressed in #1389, but we should make some decisions on how we refer to the rules for estimating the prior.

### Describe the solution you'd like

Rename `deterministic_matching_rules` in [`estimate_probability_two_random_records_match`](https://moj-analytical-services.github.io/splink/linker.html#splink.linker.Linker.estimate_probability_two_random_records_match) to `rules_to_estimate_prior`. (thanks to @zslade for the suggestion)

We should also change the references to `deterministic_rules` in the tutorials and example notebooks to ensure consistency across the docs to something more explicit. Possibly `rules_to_estimate_prior`, but I haven't thought too hard about the naming at this stage.

**Comment by RobinL** [comment]
I agree this is a bit confusing.  It should be clear that these are rules to estimate the prior, but I'm not sure about the suggestion for two reasons:

1. We don't use the terminology `prior` in the Splink public API itself.  Expert users are likely to be familiar with this terminology from reading record linkage theory, but I'm not sure other users would be familiar with it.  Instead, we use [probability_two_random_records_match"](https://github.com/moj-analytical-services/splink/blob/71b89368c094906f22f20f3369c91b7fb25f7b4e/splink/files/settings_jsonschema.json#L25)
2. This only appears as an argument to the [https://moj-analytical-services.github.io/splink/linker.html#splink.linker.Linker.estimate_probability_two_random_records_match](https://github.com/moj-analytical-services/splink/blob/71b89368c094906f22f20f3369c91b7fb25f7b4e/splink/linker.py#L3070).  Since it's an argument to the function, it's arguably tautological to repeat it in the function call.

The other place it appears is the docs, e.g. [here](https://moj-analytical-services.github.io/splink/demos/04_Estimating_model_parameters.html#estimation-of-probability_two_random_records_match).  The first time it appears is as a variable assignment:

```
deterministic_rules = [
    "l.first_name = r.first_name and levenshtein(r.dob, l.dob) <= 1",
...
```

We could certainly rename this to be more specific, which may help; it would also have the advantage of not breaking backwards compatibility

**Comment by RossKen** [comment]
Yea that makes sense. Happy for it to leave the function argument and make it a terminology convention (possibly overlapping with Sam's issue #1401) in the docs and examples (and probably in our own pipelines too to make things consistent).
