### ISSUE TITLE
[FEAT] Add match probability to waterfall chart tooltip

### ISSUE THREAD

**Issue by RossKen** [moj-analytical-services/splink#1549]
### Is your proposal related to a problem?

Current Waterfall chart tooltip
<img width="446" alt="image" src="https://github.com/moj-analytical-services/splink/assets/26222179/fea83c97-0877-4f6f-b142-e75a4dc617a3">

We provide the cumulative match weight in the tooltip, it feels like cumulative match probability would also be helpful. Particularly for the final (total match score) bar.

### Describe the solution you'd like

Add cumulative match probability to tooltip

**Comment by samnlindsay** [comment]
"Adjusted match score" _is_ the cumulative match probability. So really I guess it just needs renaming to be clearer.

**Comment by RossKen** [comment]
Ah, sorry - being a moron. I had assumed that was the cumulative match weight

**Comment by samnlindsay** [comment]
No, but it does raise the issue around language when referring to match score as opposed to match probability. This is largely mitigated by focusing on match weights (-inf to +inf) rather than probabilities/match scores (0 to 1) but we generally want to avoid quoting probabilities because we know they're not valid.

**Comment by RossKen** [comment]
Closed by #1550
