### ISSUE TITLE
[FEAT] Improve ExplodingBlockingRule performance

### ISSUE THREAD

**Issue by aymonwuolanne** [moj-analytical-services/splink#2384]
Reviewing the SQL produced to block on an `ExplodingBlockingRule` in the latest version of Splink shows more joins than I expected. In the source code [here](https://github.com/moj-analytical-services/splink/blob/master/splink/internals/blocking.py#L460-L470) there are two left joins of the exploded_id_pair_table to the left and right input tables, but I'm pretty sure this is redundant? The columns needed to define `join_key_l` and `join_key_r` are already in the `exploded_id_pair_table`. The only situation where you wouldn't get exactly the same result is when there are multiple rows in the input data with the same `unique_id`, but all this would change is creating duplicate rows in the blocked id pairs table, which the user probably doesn't want anyway. 

Secondly, when I've been using exploding blocking rules with Spark, I've noticed the execution plan for the blocking step becomes extremely complex. I wonder if adding the `__splink__marginal_exploded_ids_blocking_rule` tables to the list of tables to persist would help?

**Comment by RobinL** [comment]
Thanks for spotting, yes - it's definitely plausible there's redundant code here.

In Splink 4, we changed the execution/materialisation so that all the ID pairs (exploding or not) get materialised, see [here](https://github.com/moj-analytical-services/splink/pull/2231).  So perhaps that's what doubled up on some of the logic

I didn't test performance on exploding rules, but I'd certainly be interested in whether Splink4 is better or worse.  My huch is that once the superfluous code is fixed, i think there's a reasonable chance that performace in Splink4 may be a fair bit higher

**Comment by aymonwuolanne** [comment]
Thanks Robin, PR looks good! Did you have any thoughts about adding the marginal exploded ids tables to the list of tables to persist in the Spark backend?
