### ISSUE TITLE
org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStageX grows beyond 64 KB

### ISSUE THREAD

**Issue by mamonu** [moj-analytical-services/splink#81]
There seems to be an issue with some of the calculation stages during the 
Maximisation step when running through the sparklink normal flow in AWS Glue.
It doesnt stop the calculations and the job finishes sucessfully but perhaps this merits attention
in the sense that we dont know what happens when a "Whole-stage codegen disabled for plan X"

an example from the logs :

`20/02/26 17:01:01 ERROR CodeGenerator: failed to compile: org.codehaus.janino.InternalCompilerException: Compiling "GeneratedClass": Code of method "processNext()V" of class "org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage15" grows beyond 64 KB
20/02/26 17:01:01 **WARN WholeStageCodegenExec: Whole-stage codegen disabled for plan** (id=15):`

part of Codegen follows  : 

`
 *(15) Project [(((((((((((0.013465756550431252 * CASE WHEN (CASE WHEN (isnull(PERNAME1#69) || isnull(PERNAME1#1446)) THEN -1 WHEN (UDF:jaccard_sim(UDF:QgramTokeniser(PERNAME1#69), UDF:QgramTokeniser(PERNAME1#1446)) > 0.84) THEN 2 WHEN (UDF:jaccard_sim(UDF:QgramTokeniser(PERNAME1#69), UDF:QgramTokeniser(PERNAME1#1446)) > 0.7) THEN 1 ELSE 0 END = -1) THEN 1.0 WHEN (CASE WHEN (isnull(PERNAME1#69) || isnull(PERNAME1#1446)) THEN -1 WHEN (UDF:jaccard_sim(UDF:QgramTokeniser(PERNAME1#69), UDF:QgramTokeniser(PERNAME1#1446)) > 0.84) THEN 2 WHEN UDF:QgramTokeniser(PERNAME1#1446)) > 0.84) THEN 2 WHEN (UDF:jaccard_sim(UDF:QgramTokeniser(PERNAME1#69), 
` 

and it goes for ever like that ...

**Comment by mamonu** [comment]
Some proposed solutions for this from SO:

1. In the config: 
`spark = SparkSession.builder.master('local').appName('blah')\
        .config('spark.sql.codegen.wholeStage', 'false')\ ## <-- add this line
        .getOrCreate()`

2.  adding extra "checkpoints" in code.

**Comment by mamonu** [comment]
looking this a bit more today it seems that when `spark.sql.codegen.wholeStage` is on there is
a bit of an improvement in speed but nothing would break if we just turned it off.

https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-whole-stage-codegen.html

**Comment by RobinL** [comment]
What's weird about this is there is a persist on df_gammas which should prevent this.

The problem is happening because the whole of the 'generate gammas' code and the 'compute expectation' is being bundled into a single project statement. 

Solutions:
- the df -> rdd -> df trick might work:

https://stackoverflow.com/questions/50891509/apache-spark-codegen-stage-grows-beyond-64-kb

- split the job out into a 'compute gammas and persist to s3', and 'read from s3 and compute expectation' .   since we're already repartition to 200 when we write out df_e this might actually not slow things down much
