### ISSUE TITLE
Tests fail outside of github workflow

### ISSUE THREAD

**Issue by ADBond** [moj-analytical-services/splink#829]
`test_salting_len.py` fails in some envirnoments outside the one running in the github actions pipeline - specifically this is the case on the analytical platform.

Specifically the line https://github.com/moj-analytical-services/splink/blob/00d7acb3bf515ca58376b8a091ed45817d94ee7f/tests/test_salting_len.py#L79 fails, with more indices appearing on the LHS than the right.

**Comment by ADBond** [comment]
Appears to have been the case since at least `3.0.0`

**Comment by ThomasHepworth** [comment]
Ok, so, this issue appears on `pyspark==3.1.1` (from my testing, anyway - there's likely other versions of pyspark is breaks on too) and it looks to be very similar to [#Issue 599](https://github.com/moj-analytical-services/splink/issues/599).

Most users will never encounter this issue as they'll just install the latest version of pyspark anyway. The AP however, currently requires us to run v3.1.1, so we are hitting another `random()` + CTE bug.

This issue is fixed - as in the duckdb version - by simply materialising the tf_with_concat df [here](https://github.com/moj-analytical-services/splink/blob/master/splink/linker.py#L993). Unfortunately, this kind of defeats the point of `linker.predict()` and the "only materialise the final output" ethos.

At present, the fix for this is simply to tell users to upgrade their pyspark version if they wish to use salting. 

However, it's not at all obvious that something is wrong, if you're just running splink's `predict()` statement without re-running the model to check if your outputs are consistent.

A potential solution would be to check if the user is running an invalid version of spark and requesting salting. If Y, then  cancel the pipeline and tell them this is invalid.

<hr>

**A quick reproducible example** -- _Make sure you're on v3.1.1_
```
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession

conf = SparkConf()

conf.set("spark.driver.memory", "4g")
conf.set("spark.sql.shuffle.partitions", "8")
conf.set("spark.default.parallelism", "8")

sc = SparkContext.getOrCreate(conf=conf)

spark = SparkSession(sc)
spark.sparkContext.setCheckpointDir("./tmp_checkpoints")

import pandas as pd
df = pd.DataFrame({"col1": range(100)})
spark_df=spark.createDataFrame(df) 
spark_df.createOrReplaceTempView("a")


sql = """
with b as (
    select col1, CEIL(random() * 3) as __splink_salt
    from a
)
select *
from b
where __splink_salt == 1
UNION ALL
select *
from b
where __splink_salt == 2
UNION ALL
select *
from b
where __splink_salt == 3
"""

spark.sql(sql).toPandas()
```
