### ISSUE TITLE
Toy Example

### ISSUE THREAD

**Issue by firmai** [moj-analytical-services/splink#882]
### What happens?

Hey, I was wondering if you could help with a simple toy linkage example with just a single text column. I have tried with and without deterministic rules with no success. 

Parameter estimates cannot be made for the following comparison(s) since they are used in the blocking rules: 
INFO:splink.expectation_maximisation:

![image](https://user-images.githubusercontent.com/26666267/200691643-2855187b-3aab-4b0c-aa07-34f69edb0b2f.png)

### To Reproduce

I have a two datasets with one column each. 
![image](https://user-images.githubusercontent.com/26666267/200691895-e144f825-bb6b-4a06-9ccf-a26c0ba54949.png)
![image](https://user-images.githubusercontent.com/26666267/200691999-260ab014-2dca-484c-b4b6-e73ce3425d78.png)

```
from splink.duckdb.duckdb_linker import DuckDBLinker
from splink.duckdb import duckdb_comparison_library as cl
settings = {
    "link_type": "link_only",
}
linker = DuckDBLinker([owner_df, ref_df], settings, input_table_aliases=["df_left", "df_right"])
session_train = linker.estimate_parameters_using_expectation_maximisation("l.own_name = r.own_name")
```

### OS:

Google Colab

### Splink version:

Latest pip version

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by firmai** [comment]
Hi @RobinL thanks for the response, I now understand. As a quick follow-up, is there a workaround or another library you might recommend for singular column matching? Thanks :)

**Comment by NickCrews** [comment]
As a hack to get around this, you could duplicate the column so you have both `own_name` and `own_name_block`. You make your blocking rules apply to `own_name_block` and your comparisons apply to `own_name`. Of course this still has the issue that it's going to be tricky for you to come up with blocking rules, since you can't just use `own_name_l = own_name_r`. You would need to do something like compare prefixes, suffixes, bag of words, sorted ngrams, etc, which isn't directly supported by splink.

OR, you could look at [dedupe](https://github.com/dedupeio/dedupe). Dedupe library has much better support for these string blocking rules, so if you don't mind

1. It being less scalable since it relies on more pure-python instead of fast SQL engines
2. It requiring manually labeled data, as opposed to splink which does unsupervised learning
3. probably some other differences I'm not thinking of

then I would explore dedupe.

**Comment by RossKen** [comment]
Reminder to add validation to settings object - warning when trying to link on a single cloumn

**Comment by RossKen** [comment]
Opened as a separate issue, so closing this
