### ISSUE TITLE
Ideas for improving caching

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/splink#961]
- Could assign a UID to each Linker(), and 'namespace' the cache within this UID e.g. tablenames `__splink__{UID}_...`

- I can't remember why we have some tables which are cached 'by name' rather than by the hash of the SQL.  This
   - Makes it easy to check whether they exist, i.e. not recreate
   - But why doesn't the normal 'does hashed sql table exist) caching check not work for this puporse
   - But it's problematic because if the underlying data changes, the cached SQL does not change.  

One way to invalidate cache would be to use a UID as above, and invalidating the cache would amount to changing the UID

See also #952

**Comment by RobinL** [comment]
Should be closed by #987

**Comment by NickCrews** [comment]
This bit me HARD today, several hours wasted when I was reusing the same database connection, but creating two different linkers from two different tables in the database. Both linkers were sharing the same cache. If the fix above doesn't end up working, can you push out a temp fix where Linker.__init__ removes all `__splink_*` tables from the DB (ie clearing the cache at the beginning of every linker)? I would rather have to re-calculate some work rather than get invalid results.

**Comment by RobinL** [comment]
All the tests are passing on 987 so it should be ok.  I've also done a pre release.  In a nutshell, each linker gets a unique id, which is used to determine all the table names.  And hence to invalidate the cache, all that's needed is for this id to change (there's a new method for that).

 But in the meantime you can use this internal method to delete the Splink created tables:
https://github.com/moj-analytical-services/splink/blob/b0979cdae2ee4c57e278b5f0cabd31aadc5771ef/splink/linker.py#L766

**Comment by RossKen** [comment]
Think this is all done so closing

**Comment by RobinL** [comment]
Yep - that's right, sorry, forgot to close
