### ISSUE TITLE
Point out Ibis as library

### ISSUE THREAD

**Issue by NickCrews** [moj-analytical-services/splink#973]
IDK if you've seen this before, but I just found https://ibis-project.org/docs/latest/, and I thought it might be intriguing to you as it seems to be solving a lot of the same problems that you are: Building complex SQL queries that can be translated into different SQL dialects. Perhaps there's something useful in there you can use!

**Comment by RobinL** [comment]
Thanks Nick - it's something I've looked at a few times and a really interesting project.  There are a couple of reasons we didn't go down that route.  I'm not sure how valid they (still) are:
- Splink relies on explicit control of some of its backends for performance reasons (e.g. breaking the lineage and repartitioning in Spark)
- Splink relies on various UDFs and (in some cases) things like array manipulation.  Not sure what the support is like in Ibis
- Ibis has it's own data manipulation API which is then translated into SQL, whereas I wanted the interface into Splink to be SQL (e.g. when the user specifies a custom SQL expression)

At one point, we were also auto-transpiling our SQL using sqlglot, but there's much less of that in Splink now, since Splink users often use backend-specific SQL that can't always be translated between dialects

**Comment by NickCrews** [comment]
Thanks for the explanation! Those points make sense.

> Splink relies on explicit control of some of its backends for performance reasons (e.g. breaking the lineage and repartitioning in Spark)

Yeah I think that probably isn't possible, or at least not easy. Probably won't every be.

> Splink relies on various UDFs and (in some cases) things like array manipulation. Not sure what the support is like in Ibis

My understanding is they don't have support, but plan to add it.

> Ibis has it's own data manipulation API which is then translated into SQL, whereas I wanted the interface into Splink to be SQL (e.g. when the user specifies a custom SQL expression)

Ibis does provide [a way to add in custom SQL](https://ibis-project.org/docs/4.0.0/api/expressions/tables/?h=sql#ibis.expr.types.relations.Table.sql). Not sure if that solves what you're talking about.

I'll close this since you've seen this :)

**Comment by NickCrews** [comment]
@cpcloud in case you want to advocate for Ibis any more here :)
